import daisyui from "daisyui";

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/**/*.{html,ts}", // Achte darauf, dass deine Templates und Typescript-Dateien einbezogen sind.
  ],
  theme: {
    extend: {},
  },
  plugins: [daisyui],
  daisyui: {
    themes: [
      {
        tag: {
          "color-scheme": "light",
          "base-100": "oklch(99% 0.005 60)",
          "base-200": "oklch(94% 0.008 60)",
          "base-300": "oklch(89% 0.01 60)",
          "base-content": "oklch(20% 0.01 30)",
          primary: "#F4CFC7",
          "primary-content": "#5D4A47",
          secondary: "#FFC98B",
          "secondary-content": "#6B3D14",
          accent: "#FFBE98",
          "accent-content": "#5A2D19",
          neutral: "#D8CFC4",
          "neutral-content": "#3C3C3C",
          info: "#D4C2CD",
          "info-content": "#56394B",
          success: "#C6C09C",
          "success-content": "#3C3F2F",
          warning: "#FFD59A",
          "warning-content": "#5C341B",
          error: "#E79796",
          "error-content": "#5A2322",
          "radius-selector": "2rem",
          "radius-field": "1rem",
          "radius-box": "0.5rem",
          "size-selector": "0.25rem",
          "size-field": "0.25rem",
          border: "1px",
          depth: "0",
          noise: "0",
        },
        nacht: {
          "color-scheme": "dark",
          "base-100": "oklch(12% 0.01 30)",
          "base-200": "oklch(9% 0.01 30)",
          "base-300": "oklch(6% 0.01 30)",
          "base-content": "oklch(88% 0.01 60)",
          primary: "#E8A090",
          "primary-content": "#2C1C1B",
          secondary: "#C4722A",
          "secondary-content": "#F9D4B6",
          accent: "#E8C07A",
          "accent-content": "#3D2A10",
          neutral: "#2A2420",
          "neutral-content": "#E0D5CC",
          info: "#6B4A60",
          "info-content": "#EDD6E8",
          success: "#4A5238",
          "success-content": "#D4E0B8",
          warning: "#7A4520",
          "warning-content": "#FFE0B0",
          error: "#7A2E2C",
          "error-content": "#FFD0CE",
          "radius-selector": "2rem",
          "radius-field": "1rem",
          "radius-box": "0.5rem",
          "size-selector": "0.25rem",
          "size-field": "0.25rem",
          border: "1px",
          depth: "0",
          noise: "0",
        },
        scuro: {
          "color-scheme": "light",
          "base-100": "oklch(100% 0 0)",
          "base-200": "oklch(95% 0 0)",
          "base-300": "oklch(95% 0 0)",
          "base-content": "oklch(20% 0 0)",
          primary: "#F4CFC7",
          "primary-content": "#5D4A47",
          secondary: "#FFC98B",
          "secondary-content": "#6B3D14",
          accent: "#FFBE98",
          "accent-content": "#5A2D19",
          neutral: "#D8CFC4",
          "neutral-content": "#3C3C3C",
          info: "#D4C2CD",
          "info-content": "#56394B",
          success: "#C6C09C",
          "success-content": "#3C3F2F",
          warning: "#FFD59A",
          "warning-content": "#5C341B",
          error: "#E79796",
          "error-content": "#5A2322",
          "radius-selector": "2rem",
          "radius-field": "1rem",
          "radius-box": "0.5rem",
          "size-selector": "0.25rem",
          "size-field": "0.25rem",
          border: "1px",
          depth: "0",
          noise: "0",
        },
      },
      {
        morning: {
          "color-scheme": "light",
          "base-100": "oklch(98% 0.012 80)",
          "base-200": "oklch(93% 0.018 75)",
          "base-300": "oklch(87% 0.024 70)",
          "base-content": "oklch(22% 0.02 40)",
          primary: "#F7B89A",
          "primary-content": "#5C2A18",
          secondary: "#F4D0A1",
          "secondary-content": "#6B3D14",
          accent: "#EFA07A",
          "accent-content": "#4A1F0F",
          neutral: "#E8D5C0",
          "neutral-content": "#3C3020",
          info: "#D9C8D8",
          "info-content": "#503450",
          success: "#C8D4A0",
          "success-content": "#3A4020",
          warning: "#F8DCA0",
          "warning-content": "#5C3818",
          error: "#F0A898",
          "error-content": "#5A2220",
          "radius-selector": "2rem",
          "radius-field": "1rem",
          "radius-box": "0.5rem",
          "size-selector": "0.25rem",
          "size-field": "0.25rem",
          border: "1px",
          depth: "0",
          noise: "0",
        },
      },
      {
        noon: {
          "color-scheme": "light",
          "base-100": "oklch(99% 0.006 95)",
          "base-200": "oklch(95% 0.01 90)",
          "base-300": "oklch(90% 0.015 85)",
          "base-content": "oklch(18% 0.005 60)",
          primary: "#F5C842",
          "primary-content": "#3C2600",
          secondary: "#88C8D8",
          "secondary-content": "#1A3F4A",
          accent: "#F09060",
          "accent-content": "#4A1E10",
          neutral: "#D0CFC0",
          "neutral-content": "#3C3C30",
          info: "#A8D4E0",
          "info-content": "#1A3840",
          success: "#B8D8A0",
          "success-content": "#284020",
          warning: "#F8D870",
          "warning-content": "#503800",
          error: "#F0A090",
          "error-content": "#501C18",
          "radius-selector": "2rem",
          "radius-field": "1rem",
          "radius-box": "0.5rem",
          "size-selector": "0.25rem",
          "size-field": "0.25rem",
          border: "1px",
          depth: "0",
          noise: "0",
        },
      },
      {
        evening: {
          "color-scheme": "light",
          "base-100": "oklch(88% 0.025 50)",
          "base-200": "oklch(82% 0.034 45)",
          "base-300": "oklch(75% 0.042 40)",
          "base-content": "oklch(16% 0.02 30)",
          primary: "#E07840",
          "primary-content": "#F8E0D0",
          secondary: "#9B5E80",
          "secondary-content": "#F0D0E0",
          accent: "#C8A040",
          "accent-content": "#3A2800",
          neutral: "#C8B49A",
          "neutral-content": "#3C2C20",
          info: "#B09090",
          "info-content": "#EEE0E0",
          success: "#8A9870",
          "success-content": "#F0F0E0",
          warning: "#D09040",
          "warning-content": "#3C2400",
          error: "#C05848",
          "error-content": "#F8E0DC",
          "radius-selector": "2rem",
          "radius-field": "1rem",
          "radius-box": "0.5rem",
          "size-selector": "0.25rem",
          "size-field": "0.25rem",
          border: "1px",
          depth: "0",
          noise: "0",
        },
      },
      {
        night: {
          "color-scheme": "dark",
          "base-100": "oklch(14% 0.03 255)",
          "base-200": "oklch(10% 0.025 255)",
          "base-300": "oklch(7% 0.02 255)",
          "base-content": "oklch(85% 0.015 240)",
          primary: "#9090E0",
          "primary-content": "#10102C",
          secondary: "#6868B8",
          "secondary-content": "#D0D0F8",
          accent: "#D4A840",
          "accent-content": "#3A2800",
          neutral: "#202840",
          "neutral-content": "#C0C8E0",
          info: "#4858A0",
          "info-content": "#C8D4F8",
          success: "#386048",
          "success-content": "#B8E0C8",
          warning: "#785020",
          "warning-content": "#FFE0A8",
          error: "#782030",
          "error-content": "#FFD0D8",
          "radius-selector": "2rem",
          "radius-field": "1rem",
          "radius-box": "0.5rem",
          "size-selector": "0.25rem",
          "size-field": "0.25rem",
          border: "1px",
          depth: "0",
          noise: "0",
        },
      },
    ],
  },
};
