module.exports = {
  content: ["./src/**/*.{html,ts}"],
  theme: {
    extend: {},
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        mechuTheme: {
          primary: "#F4CFC7",
          secondary: "#FFC98B",
          accent: "#FFBE98",
          neutral: "#D8CFC4",
          "base-100": "#FFFFFF",
          info: "#D4C2CD",
          success: "#C6C09C",
          warning: "#FFD59A",
          error: "#E79796",
        },
        light: {
          "color-scheme": "light",
          "base-100": "oklch(100% 0 0)",
          "base-200": "oklch(95% 0 0)",
          "base-300": "oklch(95% 0 0)",
          "base-content": "oklch(20% 0 0)",
          primary: "#F4CFC7",
          "primary-content": "#5D4A47",
          secondary: "#FFC98B",
          "secondary-content": "#6B3D14",
          accent: "#FFBE98",
          "accent-content": "#5A2D19",
          neutral: "#D8CFC4",
          "neutral-content": "#3C3C3C",
          info: "#D4C2CD",
          "info-content": "#56394B",
          success: "#C6C09C",
          "success-content": "#3C3F2F",
          warning: "#FFD59A",
          "warning-content": "#5C341B",
          error: "#E79796",
          "error-content": "#5A2322",
          "radius-selector": "2rem",
          "radius-field": "1rem",
          "radius-box": "0.5rem",
          "size-selector": "0.25rem",
          "size-field": "0.25rem",
          border: "1px",
          depth: "0",
          noise: "0",
        },
        dark: {
          "color-scheme": "dark",
          "base-100": "oklch(20% 0 0)",
          "base-200": "oklch(15% 0 0)",
          "base-300": "oklch(10% 0 0)",
          "base-content": "oklch(90% 0 0)",
          primary: "#B27B72",
          "primary-content": "#2A1E1D",
          secondary: "#A96B3D",
          "secondary-content": "#FFC98B",
          accent: "#B87550",
          "accent-content": "#FFBE98",
          neutral: "#3C3C3C",
          "neutral-content": "#D8CFC4",
          info: "#56394B",
          "info-content": "#D4C2CD",
          success: "#3C3F2F",
          "success-content": "#C6C09C",
          warning: "#5C341B",
          "warning-content": "#FFD59A",
          error: "#5A2322",
          "error-content": "#E79796",
          "radius-selector": "2rem",
          "radius-field": "1rem",
          "radius-box": "0.5rem",
          "size-selector": "0.25rem",
          "size-field": "0.25rem",
          border: "1px",
          depth: "0",
          noise: "0",
        },
      },
      "light",
      "dark",
    ],
  },
};
